---
import SiteLayout from '../layouts/SiteLayout.astro';
import '../styles/global.css';
const install='npm install -g @agent-qofeno/agentx-cli';
const benefits=[['01','Repository aware','Start from the files, packages, routes, and conventions that already exist.'],['02','Plan before edits','Turn a broad outcome into a visible sequence of changes before the write phase.'],['03','Terminal native','Use the commands and tools your project already trusts instead of replacing the workflow.'],['04','Verify the work','Builds, tests, type checks, and runtime feedback become part of the same loop.']];
const faqs=[['What is AgentX?','AgentX is a terminal based AI agent for building and modifying real software projects.'],['Does it work with existing repositories?','Yes. Existing code, configuration, dependencies, and conventions are treated as context before edits begin.'],['Can I use local models?','Yes. The docs cover local model runners including Ollama and LM Studio.'],['Can I review a plan first?','Yes. The intended workflow makes the plan explicit before the execution pass.']];
---
<SiteLayout title="AgentX — terminal agent for real software" description="AgentX reads your project, plans the work, executes changes, and verifies the result.">
<main><section class="hero"><div class="shell"><div class="hero-grid"><div><p class="kicker">TERMINAL AGENT · OPEN WORKFLOW</p><h1>Build with an agent that can see the whole project.</h1><p class="hero-lead">AgentX reads the repository, plans the work, changes the right files, and uses your project’s own checks to verify the result.</p><div class="actions"><a class="button" href="/docs/intro/">Start with the docs ↗</a><a class="secondary" href="https://github.com/SohailKhan0525/agentx-cli">View source</a></div><p class="proof">Open source · Windows · macOS · Linux · cloud or local models</p></div><div class="terminal"><div class="term-top"><span>agentx</span><span>plan mode</span></div><div class="term-body"><div>$ agentx</div><div class="muted">Project: ~/work/agentx</div><div class="term-line"></div><div>What should we change?</div><div class="muted">Rework the settings experience. Keep the current API.</div><div class="plan"><span>01</span> Read routes and components</div><div class="plan"><span>02</span> Map affected files</div><div class="plan"><span>03</span> Draft implementation plan</div><div class="plan"><span>04</span> Wait for confirmation ▍</div></div></div></div></div></section>
<section class="tagline"><div class="shell"><p class="kicker">THE CORE IDEA</p><h2>Understand the code before you change the code.</h2></div></section>
<section class="section"><div class="shell"><div class="section-head"><div><p class="kicker">WHY AGENTX</p><h2>Less guessing. More useful context.</h2></div><p>Designed for repositories that have history, constraints, and a real release process.</p></div><div class="benefits">{benefits.map(([n,t,d])=><article class="benefit"><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section class="dark"><div class="shell"><div class="section-head"><div><p class="kicker">THE LOOP</p><h2>One workspace. Four deliberate moves.</h2></div><p>Inspired by the practical, terminal-centered clarity of modern coding agents such as OpenCode, while keeping AgentX’s own workflow and identity.</p></div><div class="loop">{['Plan the outcome','Read the workspace','Execute the change','Verify the result'].map((t,i)=><div class="loop-row"><span>0{i+1}</span><h3>{t}</h3><p>{['Define what done means and identify the files that matter.','Inspect source, dependencies, configuration, and project conventions.','Use the terminal and tools to make a focused, reviewable change.','Run the checks that matter and iterate when the project gives feedback.'][i]}</p></div>)}</div></div></section>
<section class="editorial"><div class="shell"><div class="two-col"><div><p class="kicker">WORK WITH WHAT YOU HAVE</p><h2>Keep your stack. Keep your tools. Add an agent.</h2></div><div><p>AgentX is designed to fit around the repository instead of making the repository fit around the agent.</p><a class="arrow" href="/docs/architecture/">Read the architecture →</a></div></div></div></section>
<section class="install"><div class="shell"><div class="two-col"><div><p class="kicker">INSTALL</p><h2>Open a terminal and start from the project.</h2><p>Install the CLI, enter your repository, and run AgentX. Configure a cloud provider or continue with a local model.</p><a class="arrow" href="/docs/installation/">Installation guide →</a></div><div><div class="install-box"><code>{install}</code><button id="copy" type="button">Copy</button></div><p class="proof">Then: <code>cd your-project</code> and <code>agentx</code></p></div></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><div><p class="kicker">FAQ</p><h2>Before your first session.</h2></div></div><div class="faq">{faqs.map(([q,a])=><details><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
<section class="cta"><div class="shell"><div class="cta-inner"><div><p class="kicker">START HERE</p><h2>Give the agent a real repository.</h2><p>Read the quick start, install the CLI, and keep your existing engineering workflow in charge.</p></div><a class="button-light" href="/docs/intro/">Read the docs ↗</a></div></div></section></main>
<script>const b=document.querySelector('#copy');const v='npm install -g @agent-qofeno/agentx-cli';b?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(v);b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1400)}catch{}});</script>
</SiteLayout>